# Compose Sample application image
FROM python:2.7
MAINTAINER Ed Grams <edgramswork@gmail.com>
ENV REFRESHED_AT 2017-01-01

ADD . /composeapp

WORKDIR /composeapp

RUN pip install -r requirements.txt
